let root = document.getElementById('root');
let header = document.createElement('div');
header.innerText = 'header';
root.append(header);
let sider = document.createElement('div');
sider.innerText = 'sider';
root.append(sider);
let content = document.createElement('div');
content.innerText = 'content';
root.append(content);
